name: Generate GitHub metrics
on:
  schedule:
    - cron: "0 6 * * *" # daily at 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write # ðŸ‘ˆ Required so the action can commit metrics.svg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Arman
          template: classic
          base: header, activity, community, repositories, metadata
          filename: metrics.svg

          # Plugins
          plugin_languages: yes
          plugin_achievements: yes
          plugin_calendar: yes
